name: Update Package

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  update:
    uses: spaceplay-games/unity-firebase-upm/.github/workflows/update-package.yml@main
    with:
      package_name: "com.google.firebase.storage"
      package_type: "firebase"
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
